spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/aqua
    username: ${DB_USER:postgres}
    password: ${DB_SECRET:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata